### ISSUE TITLE
Additional drivers

### ISSUE THREAD

**Issue by andrekop** [davemckelvie/things-drivers#2]
Great work with the PCF8574 and HD44870 drivers!

Are you considering to add additional drivers in this repo? If yes, I want to suggest the following ones as they also use I2C and there might be some synergies with the existing drivers:

**TCS34725 color sensor**
Existing Java libraries (not adapted for Android Things):
https://github.com/ControlEverythingCommunity/TCS34725/blob/master/Java/TCS34725.java
https://github.com/OlivierLD/raspberry-pi4j-samples/blob/master/I2C.SPI/src/i2c/sensor/TCS34725.java
https://github.com/jbyle/PI4JDevelopment/blob/master/src/main/java/be/byle/TCS34725.java

**ADS1115 ADC** (e.g., for MQ135 gas sensor)
Existing non-Java libraries:
https://github.com/adafruit/Adafruit_Python_ADS1x15
https://github.com/dirtycold/raspberrypi-ads1115
 
Other non-I2C drivers not yet available for Android Things:

**RF433**
https://github.com/majauskas/433MHz

**IR**
https://github.com/Irdroid/Irdroid-USB

**Comment by davemckelvie** [comment]
Hi, thanks for your comments and suggestions. I don't have any firm plans for adding more drivers to this repo yet. The Android Things drivers space is too new. That colour sensor looks cool though. I'll get one to experiment with.
